UHM-5628:Properly handle visit when admission entered retrospectively
PIH/openmrs-module-pihcore pull request #287
Opened 2021-08-16 17:05 UTC by mogoodrich

2021-08-16 17:41 UTC, brandones commented on api/src/main/java/org/openmrs/module/pihcore/htmlformentry/action/ReopenVisitAction.java
> +            Iterator<Visit> i = moreRecentVisits.iterator();
Can't you just

```suggestion
            moreRecentVisits.remove(visit);
```
?

2021-08-16 17:44 UTC, brandones commented on api/src/main/java/org/openmrs/module/pihcore/htmlformentry/action/ReopenVisitAction.java
> +            }
Can't you just

```suggestion
            moreRecentVisits.remove(visit);
```
?

2021-08-16 17:50 UTC, brandones commented on api/src/main/java/org/openmrs/module/pihcore/htmlformentry/action/ReopenVisitAction.java
> +            if ((moreRecentVisits == null || moreRecentVisits.size() == 0) && visit.getStopDatetime() != null) {
If it's possible for it to be null, you need to guard against it earlier so that the iterator/remove lines don't NPE

2021-08-16 17:59 UTC, brandones requested changes
A couple things to review

2021-08-17 14:29 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/pihcore/htmlformentry/action/ReopenVisitAction.java
> +            }
Duh, good call

2021-08-17 14:29 UTC, mogoodrich reviewed
Thanks @brandones , good catches... I updated, bouncing this back to you

2021-08-17 15:26 UTC, brandones approved these changes
Looks good, thanks Mark!

2021-08-17 15:26 UTC, merged