addig the translated messge to the ui
PIH/openmrs-module-pihcore pull request #456
Opened 2023-10-30 18:59 UTC by Dutervil

@dmdesimone addig the translated messge to the ui. Have a look please

2023-10-30 21:50 UTC, mogoodrich requested changes
Thanks @Dutervil  see my comment!

2023-10-30 21:50 UTC, mogoodrich commented on omod/src/main/webapp/fragments/hiv/programLocationWarning.gsp
> +             <li>${ui.message("pihcode.alert") }</li>
A small typo, the other codes are called "pihcore." (named after the module) not "pihcode.", can we change to be consistent?  Thanks!

2023-11-07 15:30 UTC, Dutervil commented
@dmdesimone Have a look please

2023-11-07 15:37 UTC, Dutervil commented
@cioan Can you test this out please?

2023-11-07 15:40 UTC, cioan commented
Looks good to me, @Dutervil !

2023-11-07 15:41 UTC, Dutervil commented
@cioan Can I merge?

2023-11-07 15:43 UTC, merged